# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='contact',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='child_contact',
            field=models.ManyToManyField(to='quickstart.Contact'),
        ),
        migrations.AddField(
            model_name='contact',
            name='last_name',
            field=models.CharField(default='lastname', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
